version: '3.8'

services:
  app:
    build:
      context: ./NangPaGo-be
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    environment:
      - ./NangPaGo-be/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./NangPaGo-fe
      dockerfile: Dockerfile
    container_name: react-front
    ports:
      - "${VITE_FRONT_SERVER_PORT}:${VITE_FRONT_SERVER_PORT}"
    environment:
      - ./NangPaGo-fe/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
