services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile-admin-be
    image: nangpago-admin-be:${APP_VERSION}
    container_name: nangpago-admin-be-green
    ports:
      - "9274:${API_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    networks:
      - nangpago-network
    volumes:
      - /Users/muncheolhyun/home-server/admin/server-logs:/logs

  frontend:
    build:
      context: ../NangPaGo-admin/
      dockerfile: Dockerfile-admin-fe
    image: nangpago-admin-fe:${APP_VERSION}
    container_name: nangpago-admin-fe-green
    ports:
      - "7529:${VITE_FRONT_SERVER_PORT}"
    networks:
      - nangpago-network

networks:
  nangpago-network:
    external: true
    driver: bridge
