services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile-app-be
    image: nangpago-app-be:${APP_VERSION}
    container_name: nangpago-app-be-blue
    ports:
      - "9173:${API_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    networks:
      - nangpago-network
    volumes:
      - /Users/muncheolhyun/home-server/app/server-logs:/logs

  frontend:
    build:
      context: ../NangPaGo-client/
      dockerfile: Dockerfile-app-fe
    image: nangpago-app-fe:${APP_VERSION}
    container_name: nangpago-app-fe-blue
    ports:
      - "7428:${VITE_FRONT_SERVER_PORT}"
    networks:
      - nangpago-network

networks:
  nangpago-network:
    external: true
    driver: bridge
