services:
  backend:
    build:
      context: ./NangPaGo-be
      dockerfile: Dockerfile-be
    image: nangpago-backend:${APP_VERSION}
    container_name: nangpago-backend-green
    ports:
      - "9173:${API_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    networks:
      - nangpago-network
    volumes:
      - /Users/muncheolhyun/home-server/server-logs:/logs

  frontend:
    build:
      context: ./NangPaGo-fe
      dockerfile: Dockerfile-fe
    image: nangpago-frontend:${APP_VERSION}
    container_name: nangpago-front-green
    ports:
      - "7428:${VITE_FRONT_SERVER_PORT}"
    networks:
      - nangpago-network

networks:
  nangpago-network:
    external: true
    driver: bridge
