services:
  nangpago:
    build:
      context: ../
      dockerfile: Dockerfile
    image: nangpago-app:${APP_VERSION}
    container_name: nangpago-app-blue
    ports:
      - "9174:${API_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    networks:
      - nangpago-network
    volumes:
      - /Users/muncheolhyun/home-server/server-logs:/logs

networks:
  nangpago-network:
    external: true
    driver: bridge
