name: CI

on:
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./NangPaGo-be/gradlew  # Gradle Wrapper 실행 권한 부여

      - name: Build with Gradle
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: test_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: cd NangPaGo-be && ./gradlew build  # 프로젝트 디렉토리로 이동 후 빌드 실행

      - name: Test Application
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: test_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: cd NangPaGo-be && ./gradlew test  # 동일 디렉토리에서 테스트 실행
