name: CI

on:
  pull_request:         # PR 생성 시 실행
    branches:
      - main            # main 브랜치로 PR 생성 시에만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # OpenJDK Temurin 배포판 지정

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test Application
        run: ./gradlew test
